language: ruby
cache: bundler
bundler_args: --jobs=3 --retry=3 --without development production
rvm: 2.3.3
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
before_script:
  - cp config/database.yml.travis config/database.yml.sample
services:
  - redis-server
  - postgresql
