language: ruby
cache: bundler
bundler_args: --jobs=3 --retry=3 --without development production
rvm: 2.3.3
script:
  - bundle exec rake db:test:prepare
  - xvfb-run bundle exec rspec
before_script:
  - cp config/database.yml.sample config/database.yml
services:
  - redis-server
  - postgresql
